### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by welschoff** [welschoff/worth-watching-series#2]
<img width="253" alt="Screenshot 2021-11-22 at 20 21 33" src="https://user-images.githubusercontent.com/90267486/142922320-39e4dc81-e289-400f-9851-4f44c6df5836.png">

### Tasks

- [ ] Create input for username
- [ ] Create input for password
- [ ] Create Login Button
- [ ] Add Logo
