### ISSUE TITLE
Create Popular Page

### ISSUE THREAD

**Issue by welschoff** [welschoff/worth-watching-series#3]
<img width="257" alt="Screenshot 2021-11-22 at 20 29 37" src="https://user-images.githubusercontent.com/90267486/142923291-d8bac7c6-5244-4da7-b752-28ae19fbe066.png">

### Tasks

- [ ] fetch popular tv shows from API
- [ ] Create a fixed navbar 
- [ ] Create a sidebar 
- [ ] Create a search button(onClick navigate to Search Page)
