### ISSUE TITLE
Create My series Page

### ISSUE THREAD

**Issue by welschoff** [welschoff/worth-watching-series#6]
<img width="242" alt="Screenshot 2021-11-23 at 15 30 00" src="https://user-images.githubusercontent.com/90267486/143042892-0e4aeab3-1f6e-4baa-a231-3405aecb8999.png">

###Tasks

- [ ] show all Series I've added to watchlist
- [ ] save data in MongoDB

### As a user

- [ ] I want to create my own rating
- [ ] I want to see how many season I watched
